version: '3'
services:
  express:
    build:
      context: ./server
    container_name: express
    ports:
      - '3000:3000'
    volumes:
      - ./source:/source
      - /source/node_modules
    restart: 'unless-stopped'